INSERT INTO profanity (name) values ('Asshole')
INSERT INTO profanity (name) values ('Bitch')
INSERT INTO profanity (name) values ('Cunt')
INSERT INTO profanity (name) values ('Chode')
INSERT INTO profanity (name) values ('Dick')
INSERT INTO profanity (name) values ('Douchebag')
INSERT INTO profanity (name) values ('Faggot')
INSERT INTO profanity (name) values ('Fudgepacker')
INSERT INTO profanity (name) values ('Fuck')
INSERT INTO profanity (name) values ('Homo')
INSERT INTO profanity (name) values ('Jerkoff')
INSERT INTO profanity (name) values ('Minge')
INSERT INTO profanity (name) values ('Nigger')
INSERT INTO profanity (name) values ('Niglet')
INSERT INTO profanity (name) values ('Shit')
INSERT INTO profanity (name) values ('Twatwaffle')

INSERT INTO word_list (name) values ('Example Word List')
INSERT INTO word_list (name) values ('Blank Word List')

INSERT INTO profanity_word_list (word_list_id, profanity_id) values (1, 1)
INSERT INTO profanity_word_list (word_list_id, profanity_id) values (1, 2)
INSERT INTO profanity_word_list (word_list_id, profanity_id) values (1, 9)
INSERT INTO profanity_word_list (word_list_id, profanity_id) values (1, 15)
INSERT INTO profanity_word_list (word_list_id, profanity_id) values (1, 16)